name: Nx Cloud
on:
  push:
    branches:
      - main
env:
  NX_CLOUD_ACCESS_TOKEN: OTVkYTViNWQtYWI0OC00OGRlLTkwNmUtMzc5OTgzYmFiN2YyfHJlYWQ=
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: false
      - run: pnpm install
      - run: pnpm nx -- run-many --target=build --parallel --max-parallel=3 --all
      - run: pnpm nx -- run-many --target=test --parallel --max-parallel=2 --all
